---
# tasks file for ansible-podman container-create
# Variables:
# container_name (required): Name to be given to the container

- name: Remove container
  command: "podman rm {{ container_name }}"
  become: yes
  register: podman_container_rm_res
  changed_when: "podman_container_rm_res.rc == 0"
  failed_when: "podman_container_rm_res.rc != 0 and ('no such container' not in podman_container_rm_res.stderr)"

- name: Fill podman_container_rm
  set_fact:
    podman_container_rm: "{{ podman_container_rm_res.stdout }}"

...
