---
# tasks file for ansible-podman

- name: Prune pods
  command: "podman pod rm {{ '-f' if (force is defined and force) else ''}}"
  become: yes
  register: podman_volume_rm_res
  changed_when: "podman_volume_rm_res.rc == 0"
  failed_when: "podman_volume_rm_res.stdout is undefined"

- name: Fill podman_volume_rm
  set_fact:
    podman_volume_rm: "{{ podman_volume_rm_res.stdout }}"

...
