---
# tasks file for ansible-podman

- name: Set ports to publish
  set_fact:
    publish_str: "{{ pod_ports | default('') }}"

- name: Create new pod
  command: "podman pod create --name {{ pod_name }} --publish {{ publish_str }}"
  become: yes
  register: podman_pod_create_res
  changed_when: "{{ podman_pod_create_res.rc == 0 }}"
  failed_when: "{{ podman_pod_create_res.stdout is undefined }}"

- name: Fill exists
  set_fact:
    podman_pod_create: "{{ podman_pod_create_res.stdout }}"

...
