---
# tasks file for ansible-podman

- name: Set pod ports to publish
  set_fact:
    ports_str: "{{ ports_str | default('') }}{{ item }}{{ '' if ansible_loop.last else ',' }}"
  loop: "{{ pod_ports }}"
  loop_control:
    extended: yes
  when: pod_ports is defined

- name: TODO REMOVE Debug ports_str
  debug:
    msg: "ports_str: {{ ports_str }}"

- name: Create pod {{ pod_name }}
  command: "podman pod create --name {{ pod_name }} {{ '--publish ' + ports_str | default('') }}"
  become: yes
  register: podman_pod_create_res
  changed_when: "{{ podman_pod_create_res.rc == 0 }}"
  failed_when: "{{ podman_pod_create_res.rc != 0 }}"

- name: Fill podman_pod_create
  debug:
    msg: "podman_pod_create_res: {{ podman_pod_create_res }}"
  when: "podman_pod_create_res is defined"

- name: Fill podman_pod_create
  set_fact:
    podman_pod_create: "{{ podman_pod_create_res.stdout }}"

...
