---
# tasks file for ansible-podman
# Variables:
# volume_name (required): Volume to create

- name: Podman Run
  command: "podman run -dt {{ '-v'+ named_volumes if named_volumes is defined else '' }} --pod {{ pod_name }} --name {{ container_name }} {{ image_name }}"
  become: yes
  register: podman_run_res
  changed_when: "podman_run_res.rc == 0"
  failed_when: "podman_run_res.rc != 0 and ('file exists' not in podman_run_res.stderr)"

- name: Fill podman_run
  set_fact:
    podman_run: "{{ podman_run_res.stdout }}"

...
