---
# tasks file for ansible-podman

- name: Prube volumes
  command: "podman volume prune -f"
  become: yes
  register: podman_pod_create_res
  changed_when: "{{ podman_pod_create_res.rc == 0 }}"
  failed_when: "{{ podman_pod_create_res.stdout is undefined }}"

- name: Fill podman_pod_create
  set_fact:
    podman_pod_create: "{{ podman_pod_create_res.stdout }}"

...
